- name: Check fzf installation status
  stat:
    path: "{{ DEFAULT_TOOL_LOCATION }}/fzf"
  register: FZF_INSTALLATION_STATUS

- name: Check fzf version
  shell: fzf --version | cut -d' ' -f1
  register: CURRENT_FZF_VERSION
  changed_when: false
  when: FZF_INSTALLATION_STATUS.stat.exists

- name: Skipping if fzf is latest version
  meta: end_play
  when: FZF_INSTALLATION_STATUS.stat.exists and CURRENT_FZF_VERSION.stdout is version(EXPECTED_FZF_VERSION,'>=')

- name: Download and install latest fzf
  unarchive:
    src: https://github.com/junegunn/fzf/releases/download/{{ EXPECTED_FZF_VERSION }}/fzf-{{ EXPECTED_FZF_VERSION }}-linux_amd64.tar.gz 
    dest: "{{ DEFAULT_TOOL_LOCATION }}"
    remote_src: yes
  become: yes

